name: Test And Upload Kouyou Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run : |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Test with pytest
      run: pipenv run python -m pytest --doctest-modules --junitxml=junit/test-results-3-x.xml
    - name: Upload pytest test results
      uses: actions/upload-artifact@master
      with:
        name: pytest-results-3-x
        path: junit/test-results-3-x.xml
      if: always()
        