name: CI/CD for Kouyou Package

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup .env file
          run: |
            touch .env 
            python "import os; print(os.environ['GOOGLE_PROJECT_ID']"
            
            echo "export GOOGLE_PROJECT_ID="${{ secrets.GOOGLE_PROJECT_ID }}
            echo "export GOOGLE_PRIVATE_KEY_ID="${{ secrets.GOOGLE_PRIVATE_KEY_ID }}
            echo "export GOOGLE_PRIVATE_KEY="${{ secrets.GOOGLE_PRIVATE_KEY }}
            echo "export GOOGLE_CLIENT_EMAIL="${{ secrets.GOOGLE_CLIENT_EMAIL }}
            echo "export GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}
            echo "export GOOGLE_CLIENT_X509_CERT_URL="${{ secrets.GOOGLE_CLIENT_X509_CERT_URL }}
            pwd
            cat .env
            ls -la
